language: java
jdk: openjdk8
env:
  global:
  - secure: JZj8oAM9iXiK/DL8lEr5mE9i/vaCeSfDxty0xbf5sCyXEB1XD34k+Y0B6WWb3BcF+nSSyUFDywE+lPIwmDVXR9NaQmzF3hijbP1iSJdfzYPvHT38ECpyCuiILPyqNxaZpOmR+qwwlKMRbn7auElsAMdGa1ELGoxuf73eKqcksJ7Og2Gekto/oeQx+zuEINW3V5z/omDRNHvs3cdID6ogHUnyL8gCijCVZ9tWQh5YCqhmPrhsboiQzNnk86ZbqBrQFBmEubU5YlBhLwx4Faj2FgKt22Scw1GHSlz9ReD2nfslSLyIHCkbraMDQ+/Bjo1SaSmVRb6zpRgnYGD2g/RZOxKIzsPMOj+GqorIu4Wmyi6czwlEC7oTLWK7MKXpVg+h6bIdunzB20tOYTvogwOhtPPFio4IQMWfOQHIuAbiyOCISfTtRRY2VcVVrOyakQNefsXb2FSrF1fJ8jQToNt6OT4zr8j29T6sw5a8rLCqK8ooSRfYVAzZTJkKe8HP/0Uu6kU4Z8VOVjCKSDCcwjrAaPgZe5n+1OsHtvIVWAEFe2tCDkgnpLbl0TlXV0b9klAC/xdszFxO2ZsnQJ8XVD5eiNXpEMllBfrJ4R532RyKp/RNLd/syL/4n7ZM1eHSDC1lCkg7mK+F4+aMd3BsXNMjpOQNkBbPYeupc2TLqpGpkT8=
  - secure: Z7/MsnPyFaTjxJ4/N4FubDoORNwNja0cbKYdPrxMbj8/ptp9bYSLCiZKj29cgd0sNXQDmcvfaTN8SyJud65SyF9VD+T2V+2a3bf1cUtI29H/OMTzBKbYIPmh0oSWlIy1Piiy75BUVfQvGG9iDJHrt7kBwTx4QBeOas338Ve+E9BJqZoTG8PptyRaHqb515c+HTTGsl2Xc5U87wQeJTzw/FyblFx87uCDCYviuI8qndFX+wLIMAFlnx5+Mm7ofWg2PG5TAXuEFM46mWuoeHyG0tlP3f0O4mNW/wY3uvgF6wVuYUOi6AdRQgl4v4/zSsP6NOLdT+hw2kWCfbSqI+L/QqU6jIlIkFRBueIIsQ2PapusrKHAA/eZcea5FIvUbv+wVpFzsl/RBw5NIVDzSZ7cKbZtMdzDnxFWSSNEcPNssBw0n+quxcdrmonFOER3sngm19TNm7Mn/teq4bWpwBklGK1VgLNQk/CWb50TSpdtNtyV2nT6PrRlF/G3x9pCAg5C17cxWTA68SVTMKKwLI8CkQbytj1kRMlQCp/p60AS8s/KYrfi993FoPTPqbGwKfhb+7mNR228jsj6eY8UjgDmolfhpmpQReK0kSc3AcmNwHGqgUhfrNuYNLXPjnjJJbQ6F/U1zi3GTiRByQlvd6FYlEw/3lXSLlf+W7gH/6AcNxs=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.gradle/mongo"
deploy:
  provider: script
  script: "./gradlew bintrayPublish"
  skip_cleanup: true
  on:
    tags: true
