version: "3.8"
services:
  orientdb:
    image: library/orientdb:3.1.13
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
    ports:
      - 2480:2480
      - 2424:2424
    command: ["/orientdb/bin/server.sh", "-Dstorage.diskCache.bufferSize=1200", "-Dstorage.useWAL=false", "-Dtx.useLog=false"]
