version: "3.8"
services:
  orientdb:
    image: library/orientdb:3.0.37
    mem_limit: 8g
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
    ports:
      - 2480:2480
      - 2424:2424

volumes:
  dbvolume:
