version: "3.8"
services:
  orientdb:
    image: library/orientdb:3.0.25
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
    ports:
      - 2480:2480
      - 2424:2424
    volumes:
      - dbvolume:/orientdb/databases

volumes:
  dbvolume:
