version: "3.8"
services:
  postgres:
    image: postgres:13.2
    mem_limit: 8g
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:5
    depends_on:
      - postgres
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  dbvolume:
